name: Build Frahoosh APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Install Linux packages
        run: |
          sudo apt update
          sudo apt install -y \
            git \
            zip \
            unzip \
            autoconf \
            automake \
            libtool \
            pkg-config \
            cmake \
            libffi-dev \
            libssl-dev \
            zlib1g-dev \
            libncurses5-dev \
            libncursesw5-dev \
            libltdl-dev

      - name: Install Buildozer
        run: |
          python -m pip install --upgrade pip
          pip install buildozer==1.5.0
          pip install cython==0.29.37

      - name: Prepare Buildozer Android SDK
        run: |
          export SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"

          mkdir -p "$SDK_ROOT"

          if [ -f "$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager" ]; then
            export SDKMANAGER="$SDK_ROOT/cmdline-tools/latest/bin/sdkmanager"
          else
            export SDKMANAGER="$(find "$SDK_ROOT" -name sdkmanager -type f | head -n 1)"
          fi

          echo "SDKMANAGER=$SDKMANAGER"

          if [ -z "$SDKMANAGER" ]; then
            echo "sdkmanager not found"
            exit 1
          fi

          yes | "$SDKMANAGER" --licenses || true

          "$SDKMANAGER" \
            "platform-tools" \
            "platforms;android-35" \
            "build-tools;35.0.0" \
            "build-tools;37.0.0"

      - name: Verify AIDL
        run: |
          SDK_ROOT="$HOME/.buildozer/android/platform/android-sdk"

          echo "Checking Android SDK:"
          find "$SDK_ROOT/build-tools" -maxdepth 2 -name aidl -type f -print

          test -f "$SDK_ROOT/build-tools/37.0.0/aidl"

          "$SDK_ROOT/build-tools/37.0.0/aidl" --version

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: frahoosh-apk
          path: bin/*.apk
          if-no-files-found: error
