name: Build Frahoosh Android APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: "17"

      - name: Build APK
        working-directory: android
        run: |
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Inspect APK
        if: always()
        run: |
          echo "================================"
          echo "APK FILES"
          echo "================================"

          find "$GITHUB_WORKSPACE" \
            -type f \
            -name "*.apk" \
            -print

          echo "================================"
          echo "APK INFO"
          echo "================================"

          for apk in $(find "$GITHUB_WORKSPACE" -type f -name "*.apk"); do
            echo "--------------------------------"
            echo "FILE: $apk"
            echo "--------------------------------"

            ls -lh "$apk"

            echo "FILE TYPE:"
            file "$apk"

            echo "APK CONTENT:"
            unzip -l "$apk" | head -50
          done

          echo "================================"
          echo "ANDROID SDK"
          echo "================================"

          echo "ANDROID_HOME=$ANDROID_HOME"

          echo "BUILD TOOLS:"
          ls -la "$ANDROID_HOME/build-tools" || true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: frahoosh-android-debug
          path: android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
