name: Build Frahoosh APK

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Pull official Buildozer image
        run: |
          docker pull ghcr.io/kivy/buildozer:latest

      - name: Build APK
        run: |
          mkdir -p "$HOME/.buildozer"

          docker run --rm \
            --volume "$HOME/.buildozer:/home/user/.buildozer" \
            --volume "$GITHUB_WORKSPACE:/home/user/hostcwd" \
            ghcr.io/kivy/buildozer:latest \
            android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: frahoosh-apk
          path: bin/*.apk
          if-no-files-found: error
